// v1.3.0 Second Arc — additive expansion built on the existing scene and case systems.
const secondArcClues={
 C006:['Kad pesanan Balai Komuniti asalnya dikepit pada papan pesanan.','Selepas menyemak pesanan, Kak Suri meletakkan kad itu di sebelah dulang biru.','Dulang biru dipindahkan ke rak penyejuk sebelum roti dibungkus.','Pembantu penghantaran hanya mengambil kotak yang sudah siap dan tidak mengambil kad pesanan.','Kad pesanan ditemui di bawah dulang biru pada rak penyejuk.'],
 C007:['Senarai belian menyebut dua tomato merah.','Senarai itu juga menyebut seikat sayur hijau.','Tiga limau kecil termasuk dalam senarai.','Tiada minuman berbungkus atau makanan dalam tin dalam pesanan tersebut.','Resit gerai mengesahkan pesanan itu untuk Balai Komuniti.'],
 C008:['Label bekas menyatakan kucing oren berkolar biru mempunyai temujanji pada pukul 10:00.','Rekod menyatakan ia datang untuk pemeriksaan biasa.','Selepas pemeriksaan, Dr. Hana mengarahkan kucing itu berehat di Bilik Rehat 2.','Seorang pembantu melihat kucing berkolar biru dibawa melalui pintu hijau.','Kad Bilik Rehat 2 sepadan dengan pesakit pukul 10:00.'],
 C009:['Notis A ialah versi lama dan menunjukkan masa serta lokasi asal.','Notis B mempunyai tanda kemas kini dan masa serta lokasi baharu.','Puan Suraya menerangkan bahawa tempat aktiviti berubah kerana penyelenggaraan.','Log pejabat menunjukkan notis baharu dicetak selepas perubahan dibuat.','Jadual Dewan Utama sepadan dengan maklumat Notis B.'],
 C010:['Rekod Kedai Roti menunjukkan kotak kenangan meninggalkan kedai dengan reben kuning.','Kad laluan pasar mengesahkan kotak dikutip selepas singgah di Pasar Bayuraya.','Nota serahan klinik merekodkan kotak diteruskan menuju Balai Komuniti.','Log Balai Komuniti menyatakan kotak dihantar ke Dataran Bayuraya sebelum acara.','Ketika hujan renyai, barang kertas dialihkan ke kawasan berbumbung dan kotak bereben kuning berada di sisi pentas.']
};
const secondArcCases=[
 {id:'C006',number:'KES 006',title:'Misteri Kad Pesanan Pagi',difficulty:'⭐⭐⭐ Jejak Teratur',location:'Kedai Roti Bayuraya',scene:'bakery',character:'Kak Suri',portrait:'assets/characters/kak-suri.webp',maxStars:4,maxXP:250},
 {id:'C007',number:'KES 007',title:'Misteri Bakul Tanpa Nama',difficulty:'⭐⭐⭐⭐ Jejak Cekap',location:'Pasar Bayuraya',scene:'market',character:'Encik Hafiz',portrait:'assets/characters/encik-hafiz.webp',maxStars:4,maxXP:290},
 {id:'C008',number:'KES 008',title:'Misteri Kucing Kolar Biru',difficulty:'⭐⭐⭐⭐ Jejak Bijak',location:'Klinik Haiwan Bayuraya',scene:'vetClinic',character:'Dr. Hana',portrait:'assets/characters/dr-hana.webp',maxStars:4,maxXP:310},
 {id:'C009',number:'KES 009',title:'Misteri Notis Berganda',difficulty:'⭐⭐⭐⭐⭐ Jejak Bernas',location:'Balai Komuniti Bayuraya',scene:'communityHall',character:'Puan Suraya',portrait:'assets/characters/puan-suraya.webp',maxStars:5,maxXP:340},
 {id:'C010',number:'KES 010',title:'Misteri Kotak Kenangan',difficulty:'⭐⭐⭐⭐⭐ Jejak Pakar',location:'Dataran Bayuraya',scene:'memoryFinale',character:'Puan Suraya',portrait:'assets/characters/puan-suraya.webp',maxStars:5,maxXP:420}
];
const allCases=[...firstArcCases,...secondArcCases];
const secondCase=id=>secondArcCases.find(c=>c.id===id);
const secondIndex=id=>secondArcCases.findIndex(c=>c.id===id);
const isSecondArcCase=id=>secondIndex(id)>=0;
function isSecondArcComplete(){return secondArcCases.every(c=>isHistoricallyComplete(c.id))}

Object.assign(scenes,{
 bakery:{id:'kedai-roti-bayuraya',image:'assets/locations/kedai-roti-bayuraya.webp',alt:'Kedai Roti Bayuraya yang cerah dengan papan pesanan, dulang biru dan rak penyejuk',aspectRatio:'16 / 9',place:'Kedai Roti Bayuraya',hotspots:[{id:'papan pesanan',label:'Papan pesanan',x:3,y:7,w:20,h:31},{id:'dulang biru',label:'Dulang biru',x:34,y:51,w:13,h:13},{id:'rak penyejuk',label:'Rak penyejuk',x:49,y:16,w:19,h:47},{id:'bakul penghantaran',label:'Bakul penghantaran',x:66,y:65,w:13,h:25},{id:'kaunter roti',label:'Kaunter',x:20,y:74,w:45,h:20},{id:'buku pesanan',label:'Buku pesanan',x:21,y:48,w:12,h:11},{id:'rak roti',label:'Rak roti',x:1,y:39,w:18,h:35},{id:'kak suri',label:'Kak Suri',x:81,y:14,w:16,h:50},{id:'klip pesanan',label:'Klip pesanan di bawah dulang biru',x:48,y:63,w:10,h:10}]},
 market:{id:'pasar-bayuraya',image:'assets/locations/pasar-bayuraya.webp',alt:'Pasar Bayuraya yang bersih dengan tiga bakul, gerai sayur dan gerai buah',aspectRatio:'16 / 9',place:'Pasar Bayuraya',hotspots:[{id:'senarai belian',label:'Senarai belian',x:8,y:46,w:10,h:12},{id:'bakul a',label:'Bakul A dengan dua tomato, sayur hijau dan tiga limau',x:20,y:63,w:19,h:27},{id:'bakul b',label:'Bakul B dengan minuman berbungkus',x:42,y:64,w:18,h:27},{id:'bakul c',label:'Bakul C dengan barangan lain',x:63,y:64,w:18,h:27},{id:'gerai sayur',label:'Gerai sayur',x:1,y:14,w:29,h:31},{id:'gerai buah',label:'Gerai buah',x:33,y:12,w:27,h:31},{id:'resit pasar',label:'Resit Balai Komuniti',x:51,y:48,w:9,h:12},{id:'penimbang',label:'Penimbang',x:63,y:39,w:11,h:21},{id:'encik hafiz',label:'Encik Hafiz',x:81,y:13,w:16,h:49}]},
 vetClinic:{id:'klinik-haiwan-bayuraya',image:'assets/locations/klinik-haiwan-bayuraya.webp',alt:'Klinik Haiwan Bayuraya yang mesra dengan bekas haiwan, rekod dan dua pintu berwarna',aspectRatio:'16 / 9',place:'Klinik Haiwan Bayuraya',hotspots:[{id:'bekas haiwan',label:'Bekas haiwan kosong dengan label kolar biru',x:4,y:72,w:14,h:20},{id:'kaunter klinik',label:'Kaunter klinik',x:18,y:47,w:31,h:24},{id:'papan temujanji',label:'Papan temujanji',x:5,y:14,w:18,h:29},{id:'rekod klinik',label:'Clipboard rekod pesakit',x:27,y:34,w:10,h:10},{id:'pintu hijau',label:'Pintu hijau menuju bilik rehat',x:52,y:14,w:14,h:53},{id:'pintu biru',label:'Pintu biru',x:68,y:14,w:14,h:53},{id:'kad bilik dua',label:'Kad Bilik Rehat 2',x:51,y:2,w:16,h:10},{id:'dr hana',label:'Dr. Hana',x:83,y:15,w:14,h:49}]},
 communityHall:{id:'balai-komuniti-bayuraya',image:'assets/locations/balai-komuniti-bayuraya.webp',alt:'Balai Komuniti Bayuraya dengan dua notis, log pejabat dan pintu Dewan Utama',aspectRatio:'16 / 9',place:'Balai Komuniti Bayuraya',hotspots:[{id:'notis a',label:'Notis A versi lama',x:6,y:15,w:13,h:24},{id:'notis b',label:'Notis B dikemas kini',x:20,y:15,w:13,h:24},{id:'jadual dewan',label:'Jadual Dewan Utama',x:38,y:11,w:18,h:30},{id:'log pejabat',label:'Log pejabat',x:32,y:46,w:13,h:12},{id:'kaunter komuniti',label:'Kaunter Balai Komuniti',x:17,y:61,w:39,h:26},{id:'dewan utama',label:'Pintu Dewan Utama',x:60,y:16,w:15,h:53},{id:'bilik lain',label:'Pintu bilik lain',x:76,y:17,w:10,h:51},{id:'puan suraya',label:'Puan Suraya',x:86,y:17,w:13,h:48}]},
 memoryFinale:{id:'dataran-kotak-kenangan',image:'assets/locations/dataran-hari-bayuraya.webp',alt:'Dataran Bayuraya dengan pentas dan kawasan berbumbung semasa persiapan acara',aspectRatio:'16 / 9',place:'Dataran Bayuraya',hotspots:[{id:'pentas',label:'Pentas acara',x:6,y:26,w:27,h:38},{id:'kawasan berbumbung',label:'Kawasan berbumbung di sisi pentas',x:61,y:4,w:35,h:45},{id:'kotak kenangan',label:'Kotak kenangan bereben kuning di sisi pentas',x:67,y:65,w:13,h:18},{id:'papan acara memori',label:'Papan maklumat acara',x:41,y:17,w:19,h:30},{id:'meja pameran',label:'Meja pameran',x:12,y:64,w:22,h:19}]}
});

const routes=['Kedai Roti Bayuraya','Pasar Bayuraya','Klinik Haiwan Bayuraya','Balai Komuniti Bayuraya','Dataran Bayuraya'];
const secondTasks={
 C006:[
  {type:'scene',target:'papan pesanan',title:'Cari tempat asal kad pesanan.',prompt:'Di manakah kad pesanan Balai Komuniti dikepit pada mulanya?'},
  {type:'choice',title:'Ikuti tindakan Kak Suri.',prompt:'Selepas menyemak pesanan, di manakah Kak Suri meletakkan kad itu?',options:['Di dalam bakul penghantaran','Di sebelah dulang biru','Di atas rak roti'],answer:1},
  {type:'sequence',title:'Susun langkah penyediaan pesanan.',items:['Mula-mula semak kad pesanan.','Kemudian letakkan kad di sebelah dulang biru.','Selepas itu pindahkan dulang ke rak penyejuk.','Akhirnya bungkus pesanan yang telah siap.']},
  {type:'choice',title:'Semak tindakan pembantu penghantaran.',prompt:'Apakah yang diambil oleh pembantu penghantaran?',options:['Kotak yang sudah siap sahaja','Kad pesanan dan dulang','Semua benda di kaunter'],answer:0},
  {type:'scene',target:'klip pesanan',title:'Cari kad pesanan.',prompt:'Cari kad yang terselit di bawah dulang biru pada rak penyejuk.'}
 ],
 C007:[
  {type:'scene',target:'senarai belian',title:'Cari senarai belian.',prompt:'Senarai menyebut dua tomato merah.'},
  {type:'choice',title:'Kenal pasti sayur.',prompt:'Item manakah seikat sayur hijau?',options:['Sawi','Limau','Tomato'],answer:0},
  {type:'choice',title:'Semak kuantiti buah.',prompt:'Berapakah limau kecil dalam pesanan?',options:['Dua','Tiga','Empat'],answer:1},
  {type:'choice',title:'Tapis maklumat yang tidak relevan.',prompt:'Item manakah tidak sepatutnya ada dalam bakul?',options:['Minuman berbungkus','Dua tomato merah','Seikat sayur hijau'],answer:0},
  {type:'scene',target:'bakul a',title:'Pilih bakul Balai Komuniti.',prompt:'Cari bakul yang sepadan dengan semua ciri dan resit.'}
 ],
 C008:[
  {type:'scene',target:'bekas haiwan',title:'Periksa label bekas.',prompt:'Cari bekas pesakit pukul 10:00: kucing oren berkolar biru.'},
  {type:'scene',target:'rekod klinik',title:'Baca rekod pesakit.',prompt:'Cari rekod yang menyatakan pemeriksaan biasa.'},
  {type:'choice',title:'Fahami arahan Dr. Hana.',prompt:'Ke manakah kucing diarahkan selepas pemeriksaan?',options:['Keluar dari klinik','Bilik Rehat 2','Ruang menunggu'],answer:1},
  {type:'statement',title:'Semak kenyataan.',prompt:'Bekas kosong, tetapi rekod menunjukkan pesakit dipindahkan. Apakah kesimpulan munasabah?',options:['Kucing melarikan diri.','Kucing dipindahkan ke tempat lain di klinik.','Bekas itu tidak pernah digunakan.'],answer:1},
  {type:'scene',target:'kad bilik dua',title:'Padankan kad bilik.',prompt:'Cari kad Bilik Rehat 2 yang sepadan dengan pesakit pukul 10:00.'}
 ],
 C009:[
  {type:'scene',target:'notis a',title:'Periksa Notis A.',prompt:'Notis ini menunjukkan masa dan lokasi asal.'},
  {type:'scene',target:'notis b',title:'Cari notis terkini.',prompt:'Pilih notis yang mempunyai tanda kemas kini.'},
  {type:'choice',title:'Tanya Puan Suraya.',prompt:'Mengapakah tempat aktiviti berubah?',options:['Kerana penyelenggaraan','Kerana notis hilang','Kerana acara dibatalkan'],answer:0},
  {type:'scene',target:'log pejabat',title:'Semak masa cetakan.',prompt:'Cari log yang menunjukkan notis baharu dicetak selepas perubahan.'},
  {type:'scene',target:'jadual dewan',title:'Sahkan maklumat semasa.',prompt:'Cari jadual Dewan Utama yang sepadan dengan Notis B.'}
 ],
 C010:[
  {type:'choice',title:'Kenal pasti kotak kenangan.',prompt:'Tanda khas apakah yang dipasang pada kotak?',options:['Reben kuning','Label biru','Pelekat roket'],answer:0},
  {type:'sequence',title:'Susun laluan kotak kenangan.',items:routes},
  {type:'choice',title:'Semak nota serahan klinik.',prompt:'Ke manakah kotak diteruskan selepas Klinik Haiwan?',options:['Pasar Bayuraya','Balai Komuniti Bayuraya','Kedai Roti Bayuraya'],answer:1},
  {type:'statement',title:'Bandingkan dua masa.',prompt:'Puan Suraya melihat kotak meninggalkan Balai sebelum acara. Azzam melihatnya di sisi pentas selepas hujan bermula. Adakah kenyataan bercanggah?',options:['Ya, kotak hanya boleh berada di satu tempat.','Tidak, pemerhatian berlaku pada masa dan tempat berbeza.','Salah seorang pasti tersilap.'],answer:1},
  {type:'scene',target:'kotak kenangan',title:'Cari kotak kenangan.',prompt:'Cari kotak bereben kuning di kawasan berbumbung berhampiran sisi pentas.'}
 ]
};
const theoryAnswers={C006:'Kad bergerak bersama dulang biru lalu terselit di bawah dulang pada rak penyejuk.',C007:'Bakul yang sepadan dengan semua penerangan dan resit Balai Komuniti ialah bakul yang betul.',C008:'Kucing tidak melarikan diri; ia dipindahkan ke Bilik Rehat 2 selepas pemeriksaan.',C009:'Notis B ialah notis terkini; Notis A yang lama belum ditanggalkan.',C010:'Kotak tiba di Dataran Bayuraya lalu dialihkan ke kawasan berbumbung di sisi pentas ketika hujan renyai.'};
const evidenceRelations={C006:['asalnya di','diletakkan di sebelah','dipindahkan ke','ditemui di bawah'],C007:['menyebut','mengandungi','tidak mengandungi','disahkan oleh'],C008:['bertemu janji','menjalani','dipindahkan melalui','berehat di'],C009:['versi lama','dikemas kini','dicetak selepas','sepadan dengan'],C010:['bergerak ke','bergerak ke','diserahkan ke','dihantar ke']};

function secondTask(){return secondTasks[activeCase]?.[state.scene-1]}
function secondHelp(task=secondTask()){if(!task)return[];if(task.type==='scene')return[`Cari ${task.target} dalam gambaran lokasi.`,`Perhatikan kawasan berhampiran ${task.target}.`,`Sasaran kamu ialah ${task.target}.`];if(task.type==='sequence')return['Cari langkah yang berlaku paling awal.','Perhatikan penanda urutan atau laluan.','Pilih item seterusnya sahaja; kamu masih membuat pilihan sendiri.'];return['Baca semua pilihan sebelum menjawab.','Bandingkan masa, tempat dan penerangan penting.','Pilih jawapan yang sepadan dengan semua maklumat.']}
function secondHint(){const key=`${activeCase}-${state.scene}`,levels=state.hintLevels||(state.hintLevels={}),next=Math.min(3,(levels[key]||0)+1);if(next>(levels[key]||0))state.hintsUsed++;levels[key]=next;feedback=`Bantuan ${next}/3: ${secondHelp()[next-1]}`;wrong=false;sound('hint');persist();render()}
function completeSecondTask(){state.solved[state.scene]=true;state.cluesFound=Math.max(state.cluesFound,state.scene);feedback=`✓ Petunjuk ${state.scene}/5 ditemui.`;wrong=false;sound('clue-found');persist();render()}
function secondSceneProgress(sceneId){state.sceneProgress[sceneId]??=[];return state.sceneProgress[sceneId]}
function renderSecondSequence(task,done){const next=state.sequence.length,level=state.hintLevels?.[`${activeCase}-${state.scene}`]||0;return `<div class="sequence-progress" aria-label="Urutan pilihan">${task.items.map((_,i)=>`<span class="sequence-slot ${i<next?'filled':''}"><strong>${i+1}</strong><span>${state.sequence[i]!==undefined?task.items[state.sequence[i]]:'Pilih langkah'}</span></span>`).join('')}</div><div class="sequence-cards">${task.items.map((item,i)=>`<button data-second-fragment="${i}" ${state.sequence.includes(i)||done?'disabled':''} class="sequence-card ${level>=2&&i===next?'hint-next':''}"><b>LANGKAH ${i+1}</b><span>${item}</span></button>`).join('')}</div>${button('Tetapkan semula urutan','second-reset')}`}
function renderSecondTask(task,done,meta){const help=secondHelp(task),level=state.hintLevels?.[`${activeCase}-${state.scene}`]||0;if(task.type==='scene')return `<h2>${task.title}</h2><p>${task.prompt}</p>${renderScene(scenes[meta.scene],task.target,done,secondSceneProgress(meta.scene))}`+(done?`<div class="evidence"><small>PETUNJUK ${state.scene} DITEMUI</small>${secondArcClues[activeCase][state.scene-1]}</div>${button(state.scene===5?'Susun bukti →':'Teruskan →','next','primary')}`:'');if(task.type==='sequence')return `<h2>${task.title}</h2><p>Pilih langkah satu demi satu mengikut urutan.</p>${renderSecondSequence(task,done)}${done?`<div class="evidence"><small>PETUNJUK ${state.scene} DITEMUI</small>${secondArcClues[activeCase][state.scene-1]}</div>${button('Teruskan →','next','primary')}`:''}`;return `<h2>${task.title}</h2><p>${task.prompt}</p>${task.type==='statement'?'<div class="statement-grid"><article><b>MAKLUMAT A</b><span>Perhatikan fakta pertama.</span></article><article><b>MAKLUMAT B</b><span>Bandingkan masa dan konteks.</span></article></div>':''}<div class="choices vertical statement-options">${task.options.map((o,i)=>`<button data-second-answer="${i}" ${done?'disabled':''} class="statement-option ${done&&i===task.answer?'selected':''}"><span class="option-label" aria-hidden="true">${'ABC'[i]}</span><span class="option-text">${o}</span></button>`).join('')}</div>${done?`<div class="evidence"><small>PETUNJUK ${state.scene} DITEMUI</small>${secondArcClues[activeCase][state.scene-1]}</div>${button(state.scene===5?'Susun bukti →':'Teruskan →','next','primary')}`:''}`}
function renderSecondEvidence(done){const labels=activeCase==='C010'?[['KEDAI ROTI','PASAR'],['PASAR','KLINIK HAIWAN'],['KLINIK HAIWAN','BALAI KOMUNITI'],['BALAI KOMUNITI','DATARAN']]:[['PETUNJUK 1','PETUNJUK 2'],['PETUNJUK 2','PETUNJUK 3'],['PETUNJUK 3','PETUNJUK 4'],['PETUNJUK 4','PETUNJUK 5']];return `<h2>Sambungkan bukti.</h2><div class="connections">${labels.map(([a,b],i)=>`<div class="connection"><b>${a}</b><select data-second-link="${i}" aria-label="Hubungan ${a} kepada ${b}" ${done?'disabled':''}><option value="">Pilih hubungan…</option><option ${state.links[i]===evidenceRelations[activeCase][i]?'selected':''}>${evidenceRelations[activeCase][i]}</option><option>tidak berkaitan</option></select><b>${b}</b></div>`).join('')}</div>${button(done?'Buat deduksi →':'Semak sambungan',done?'next':'second-check','primary')}`}
function renderSecondDeduction(){const correct=theoryAnswers[activeCase],wrongA=activeCase==='C008'?'Kucing melarikan diri dari klinik.':'Barang itu telah dicuri oleh seseorang.',wrongB=activeCase==='C009'?'Semua notis memberikan maklumat yang sama.':'Tiada petunjuk yang boleh menerangkan kejadian.';return `<h2>Apakah yang sebenarnya berlaku?</h2><div class="choices vertical statement-options">${[wrongA,wrongB,correct].map((o,i)=>`<button data-second-theory="${i}" class="statement-option"><span class="option-label" aria-hidden="true">${'ABC'[i]}</span><span class="option-text">${o}</span></button>`).join('')}</div>`}
function renderSecondResult(meta){const best=record||cases[activeCase].record||state;return `<div class="celebrate result-screen"><div class="tag">${meta.number} SELESAI</div><h2>${meta.title}</h2><div class="stars" aria-label="${state.stars} daripada ${meta.maxStars} bintang">${'★'.repeat(state.stars)}${'☆'.repeat(Math.max(0,meta.maxStars-state.stars))}</div><div class="stats"><div><b>5/5</b><span>Petunjuk</span></div><div><b>+${state.xpEarned}</b><span>XP diperoleh</span></div><div><b>${best.xpEarned||0}</b><span>XP terbaik</span></div></div>${activeCase==='C010'?'<section class="milestone"><h3>🏆 FAIL KEDUA LENGKAP!</h3><p>Jejak Komuniti Bayuraya berjaya diselesaikan.</p></section>':unlockPanel()}<div class="actions">${button('Lihat Fail Kes','file','primary')}${button('Kembali ke agensi','home')}${button('Main semula','replay')}</div></div>`}
function renderSecondCase(){const meta=secondCase(activeCase),s=state.scene,done=state.solved[s];let body='';if(file)body=`<h2>Fail Kes · ${meta.title}</h2>${secondArcClues[activeCase].slice(0,state.cluesFound).map((c,i)=>`<div class="evidence"><small>PETUNJUK ${i+1}</small>${c}</div>`).join('')}${button('Kembali','closefile','primary')}`;else if(s===0)body=`<div class="eyebrow">${meta.number} · FAIL KEDUA</div><h2>${meta.title}</h2><div class="letter"><p>Satu misteri baharu menanti di ${meta.location}.</p><p>Baca setiap maklumat dan gabungkan lima petunjuk tanpa menuduh sesiapa.</p></div><div class="aynaa-card"><img src="${meta.portrait}" alt="Potret ${meta.character}" width="62" height="72"><span><b>${meta.character}</b>${meta.location}</span></div>${button('Mulakan siasatan →','next','primary')}`;else if(s>=1&&s<=5)body=renderSecondTask(secondTask(),done,meta);else if(s===6)body=renderSecondEvidence(done);else if(s===7)body=renderSecondDeduction();else if(s===8)body=`<div class="celebrate"><div class="eyebrow">✧ KES SELESAI!</div><h2>${meta.title}</h2><p>${theoryAnswers[activeCase]}</p>${button('Lihat keputusan →','next','primary')}</div>`;else body=renderSecondResult(meta);app.innerHTML=`<main><div class="topline">${button('← Agensi','home')}<span class="tag">${meta.number} · ${state.cluesFound}/5 PETUNJUK</span>${button('▤ Fail Kes','file')}</div><div class="layout"><section class="panel">${body}${feedback?`<div role="status" class="feedback ${wrong?'wrong':''}">${feedback}</div>`:''}</section><aside class="klu">${companionArt(state.status==='completed'||s>=8?'celebrate':wrong?'thinking':feedback.startsWith('Bantuan')?'hint':done?'excited':'neutral')}<div class="klu-message"><div class="eyebrow">KLU · RAKAN DETEKTIF</div><p>${s===6?'Sambungkan semua bukti sebelum membuat deduksi.':s===7?'Pilih teori yang menerangkan semua lima petunjuk.':'Baca arahan dengan teliti dan pilih sendiri.'}</p>${s>=1&&s<=5&&!done?button('☀ Bantuan '+(state.hintLevels?.[`${activeCase}-${s}`]||0)+'/3','hint'):''}</div></aside>${caseShelf()}</div></main>`}
function completeSecondCase(meta){state.status='completed';state.stars=Math.max(1,meta.maxStars-Math.floor(state.hintsUsed/3));state.xpEarned=meta.maxXP-(state.hintsUsed?30:0);state.completedAt=new Date().toISOString();if(!record||state.xpEarned>record.xpEarned||(state.xpEarned===record.xpEarned&&state.stars>record.stars))record=JSON.parse(JSON.stringify(state));state.scene=8;sound('case-complete');persist();render()}
function handleSecondClick(b){const meta=secondCase(activeCase),task=secondTask();if(b.dataset.object){state.attempts++;if(!task||task.type!=='scene'||b.dataset.object!==task.target){fail('Belum tepat. Baca arahan KLU dan cuba lagi.');return}const p=secondSceneProgress(meta.scene);if(!p.includes(task.target))p.push(task.target);completeSecondTask();return}if(b.dataset.secondAnswer!==undefined){state.attempts++;if(Number(b.dataset.secondAnswer)===task.answer)completeSecondTask();else fail('Belum tepat. Bandingkan semua maklumat dan cuba lagi.');return}if(b.dataset.secondFragment!==undefined){state.attempts++;const i=Number(b.dataset.secondFragment),expected=state.sequence.length;if(i!==expected){fail('Urutan itu belum tepat. Cari langkah yang berlaku seterusnya.');return}state.sequence.push(i);feedback='✓ Langkah seterusnya betul.';wrong=false;if(state.sequence.length===task.items.length)completeSecondTask();else{persist();render()}return}if(b.dataset.secondTheory!==undefined){state.attempts++;if(b.dataset.secondTheory==='2'&&state.cluesFound===5&&state.solved[6])completeSecondCase(meta);else fail('Teori itu belum menerangkan semua petunjuk. Cuba lagi.');return}switch(b.dataset.action){case'start':home=false;file=false;render();break;case'home':home=true;file=false;persist();render();break;case'file':file=true;render();break;case'closefile':file=false;render();break;case'next':if(safeNeedsSolve(state.scene)&&!state.solved[state.scene])return;state.scene++;state.sequence=[];feedback='';wrong=false;persist();render();break;case'hint':secondHint();break;case'second-reset':state.sequence=[];state.solved[state.scene]=false;state.cluesFound=Math.min(state.cluesFound,state.scene-1);feedback='Urutan ditetapkan semula.';persist();render();break;case'second-check':state.attempts++;if(state.cluesFound===5&&state.links.every((v,i)=>v===evidenceRelations[activeCase][i])){state.solved[6]=true;feedback='✓ Semua bukti disambungkan dengan tepat.';wrong=false;sound('board-complete');persist();render()}else fail('Sambungan belum lengkap. Semak hubungan setiap bukti.');break;case'replay':state=({C006:fresh6,C007:fresh7,C008:fresh8,C009:fresh9,C010:fresh10})[activeCase]();record=cases[activeCase].record||record;home=false;file=false;feedback='';persist();render();break}}
const safeNeedsSolve=s=>s>=1&&s<=6;

// Extend progression while retaining all First Arc historical definitions.
isCaseUnlocked=function(index){const list=allCases;return index===0||isHistoricallyComplete(list[index-1].id)};
getCompletedCaseCount=function(){return allCases.filter(c=>isHistoricallyComplete(c.id)).length};
isFirstArcComplete=function(){return firstArcCases.every(c=>isHistoricallyComplete(c.id))};
getTotalBestStars=function(){return allCases.reduce((sum,c)=>sum+getBestStars(c.id),0)};
getMaximumStars=function(){return 40};
getTotalBestXP=function(){return allCases.reduce((sum,c)=>sum+getBestXP(c.id),0)};
hasMaximumRecords=function(){return allCases.every(c=>getBestStars(c.id)>=c.maxStars)};
switchCase=function(id){const index=allCases.findIndex(c=>c.id===id);if(index<0||!isCaseUnlocked(index))return;persist();activeCase=id;state=cases[id].run;record=cases[id].record||null;clues=isSecondArcCase(id)?secondArcClues[id]:id==='C001'?clues1:id==='C002'?clues2:id==='C003'?clues3:id==='C004'?clues4:clues5;home=true;file=false;feedback='';wrong=false;persist();render()};
const secondArt=id=>`<img class="case-thumb" src="${scenes[secondCase(id).scene].image}" alt="" aria-hidden="true">`;
caseShelf=function(){const group=(title,list,offset)=>`<div class="case-arc-heading"><b>${title}</b><span>${list.filter(c=>isHistoricallyComplete(c.id)).length}/5</span></div><div class="case-list">${list.map((c,i)=>{const index=offset+i,open=isCaseUnlocked(index),status=getCaseStatus(c.id,index);return`<button class="case-card ${activeCase===c.id?'active':''} case-${status}" data-case="${c.id}" ${open?'':'disabled'} aria-label="${open?c.number+', '+c.title:c.number+', terkunci'}">${open?(c.art||secondArt(c.id)):'<svg class="icon" aria-hidden="true"><use href="#i-lock"/></svg>'}<span><strong>${c.number}</strong>${open?c.title:'???'}<small>${open?c.difficulty:'Selesaikan kes sebelumnya'}</small>${caseStatusText(c.id,index)}</span></button>`}).join('')}</div>`;return `<aside class="case-shelf" aria-label="Senarai Fail Kes"><h2><svg class="icon" aria-hidden="true"><use href="#i-folder"/></svg>Fail Kes</h2><div class="case-shelf-scroll">${group('FAIL PERTAMA',firstArcCases,0)}${group('FAIL KEDUA',secondArcCases,5)}</div></aside>`};
homeView=function(){const meta=allCases.find(c=>c.id===activeCase),second=isSecondArcCase(activeCase),summary=second?`Misteri komuniti menanti di ${meta.location}. Lima petunjuk perlu digabungkan.`:['Beg merah Aynaa hilang selepas rehat. Lima petunjuk menanti.','Dua beg pesanan mempunyai label nama yang mengelirukan.','Empat cebisan perlu disusun untuk memahami satu arahan.','Jejak bakul berubah mengikut masa dan tempat.','Kotak lencana perlu dijejaki sebelum Hari Bayuraya.'][firstArcCases.findIndex(c=>c.id===activeCase)],art=second?secondArt(activeCase):(meta.art||festivalArt),start=state.status==='completed'?'Lihat Keputusan':state.scene>0?'Sambung Siasatan':'Mula Siasatan';return `<main><div class="welcome-line">SELAMAT DATANG KE BAYURAYA · FAIL KES</div><div class="landing-layout"><section class="case-hero"><span class="file-tab">${meta.number}</span><h1>${meta.title}</h1><div class="arc-progress-wrap"><div class="arc-progress ${isFirstArcComplete()?'complete':''}"><span>${isFirstArcComplete()?'🏆 Fail Pertama Lengkap':'Fail Pertama'}</span><b>${firstArcCases.filter(c=>isHistoricallyComplete(c.id)).length}/5</b></div><div class="arc-progress ${isSecondArcComplete()?'complete':''}"><span>${isSecondArcComplete()?'🏆 Fail Kedua Lengkap':'Fail Kedua'}</span><b>${secondArcCases.filter(c=>isHistoricallyComplete(c.id)).length}/5</b></div></div><div class="case-overview"><div><span class="difficulty">${meta.difficulty}</span><p>${summary}</p></div><figure class="evidence-photo">${art}<figcaption>${second?meta.location:'Bukti utama kes'}</figcaption></figure></div>${button(start,'start','primary')}<p class="meta">Tiada had masa · Kemajuan disimpan</p>${record?`<p class="meta">★ Rekod terbaik: ${record.stars} bintang · ${record.xpEarned} XP</p>`:''}</section><aside class="klu">${companionArt(state.status==='completed'?'celebrate':'neutral')}<div class="klu-message"><div class="eyebrow">KLU · RAKAN DETEKTIF</div><p>${second?'Fail Kedua memerlukan bacaan yang lebih cermat.':'Kamu detektif utama. Saya bantu mencari petunjuk.'}</p></div></aside>${caseShelf()}</div></main>`};
unlockPanel=function(){const index=allCases.findIndex(c=>c.id===activeCase),next=allCases[index+1];if(!next||!isCaseUnlocked(index+1))return'';return `<section class="unlock-card"><span class="unlock-icon">🔓</span><div><small>KES BAHARU DIBUKA!</small><h3>${next.number} · ${next.title}</h3><p>${next.difficulty}</p></div><button data-case="${next.id}" class="primary">Lihat Kes</button></section>`};

// Map: promote four Second Arc locations without changing the master artwork.
Object.assign(locations,{bakery:{id:'bakery',label:'Kedai Roti Bayuraya',x:58,y:11,w:12,h:13,relatedCases:['C006','C010'],description:'Kedai roti komuniti yang menyediakan pesanan pagi.'},market:{id:'market',label:'Pasar Bayuraya',x:84,y:42,w:12,h:14,relatedCases:['C007','C010'],description:'Pasar komuniti yang bersih dan ceria.'},vet:{id:'vet',label:'Klinik Haiwan Bayuraya',x:32,y:60,w:12,h:14,relatedCases:['C008','C010'],description:'Klinik haiwan yang mesra dan selamat.'},community:{id:'community',label:'Balai Komuniti Bayuraya',x:51,y:70,w:13,h:14,relatedCases:['C009','C010'],description:'Pusat aktiviti dan maklumat penduduk Bayuraya.'}});
const oldLocationStatus=getLocationStatus;getLocationStatus=function(id){const links={bakery:'C006',market:'C007',vet:'C008',community:'C009'};if(links[id])return isHistoricallyComplete(links[id])?'investigated':hasCaseStarted(links[id])?'discovered':'undiscovered';return oldLocationStatus(id)};
mapCaseRows=function(location){return location.relatedCases.map(id=>{const meta=allCases.find(c=>c.id===id),index=allCases.findIndex(c=>c.id===id),open=isCaseUnlocked(index);return open?`<li><b>${meta.number}</b><span>${meta.title}</span><small>${isHistoricallyComplete(id)?'✓ Selesai':'○ Tersedia'}</small></li>`:''}).join('')};
renderMap=function(){const count=getExplorationCount(),first=isFirstArcComplete(),second=isSecondArcComplete();document.querySelector('#sound').textContent=muted?'♪ Bunyi: Mati':'♪ Bunyi: Hidup';app.innerHTML=`<main class="map-view"><div class="topline"><button data-map-home>← Agensi</button><span class="tag">PETA BAYURAYA</span><button data-map-file>▤ Fail Kes</button></div><header class="map-heading"><div><div class="eyebrow">DUNIA BAYURAYA</div><h1>Peta Bayuraya</h1><p>Terokai tempat yang telah muncul dalam siasatan kamu.</p></div><div class="exploration-count"><span>Bayuraya Diterokai</span><b>${count}/10</b><small>lokasi penting</small></div></header>${first?'<div class="map-arc-badge">🏆 <b>Fail Pertama Lengkap</b></div>':''}${second?'<div class="map-arc-badge">🏆 <b>Fail Kedua Lengkap</b></div>':''}<div class="map-layout"><section class="map-stage"><div class="map-scroll" tabindex="0" aria-label="Peta Bayuraya boleh ditatal ke sisi"><div class="map-canvas"><img class="map-art" src="assets/locations/peta-bayuraya.webp" alt="Peta bergambar bandar Bayuraya"><div class="map-hotspot-layer">${Object.values(locations).map(l=>{const status=getLocationStatus(l.id);return`<button class="map-hotspot map-${status}" style="--x:${l.x}%;--y:${l.y}%;--w:${l.w}%;--h:${l.h}%" data-location="${l.id}" aria-label="${status==='undiscovered'?'Lokasi belum ditemui':l.label+', '+locationStatusLabel(status)}"><span class="map-marker" aria-hidden="true">${status==='investigated'?'✓':status==='discovered'?'⌖':'?'}</span><span class="map-location-label">${status==='undiscovered'?'Lokasi baharu':l.label}<small>${locationStatusLabel(status)}</small></span></button>`}).join('')}</div></div></div><p class="map-mobile-guide">Leret ke sisi untuk melihat seluruh Bayuraya.</p></section>${locationPanel(selectedLocation)}</div></main>`};

// Character expansion derives discovery from case history.
Object.assign(characters,{kakSuri:{id:'kakSuri',name:'Kak Suri',role:'Pemilik Kedai Roti Bayuraya',portrait:'assets/characters/kak-suri.webp',relatedCases:['C006','C010'],relatedLocations:['bakery'],shortBio:'Menyediakan pesanan pagi dan membantu menjejaki kad pesanan Balai Komuniti.'},encikHafiz:{id:'encikHafiz',name:'Encik Hafiz',role:'Peniaga Pasar Bayuraya',portrait:'assets/characters/encik-hafiz.webp',relatedCases:['C007','C010'],relatedLocations:['market'],shortBio:'Peniaga yang membantu mengenal pasti bakul melalui senarai belian.'},drHana:{id:'drHana',name:'Dr. Hana',role:'Doktor Veterinar Klinik Haiwan Bayuraya',portrait:'assets/characters/dr-hana.webp',relatedCases:['C008','C010'],relatedLocations:['vet'],shortBio:'Doktor veterinar yang menerangkan rekod dan pemindahan pesakit dengan selamat.'},puanSuraya:{id:'puanSuraya',name:'Puan Suraya',role:'Penyelaras Balai Komuniti Bayuraya',portrait:'assets/characters/puan-suraya.webp',relatedCases:['C009','C010'],relatedLocations:['community','square'],shortBio:'Penyelaras yang memastikan maklumat aktiviti komuniti sentiasa dikemas kini.'}});
const oldCharacterDiscovered=isCharacterDiscovered;isCharacterDiscovered=function(id){const links={kakSuri:'C006',encikHafiz:'C007',drHana:'C008',puanSuraya:'C009'};if(links[id])return hasCaseStarted(links[id]);return oldCharacterDiscovered(id)};
visibleCharacterCases=function(character){return character.relatedCases.filter(id=>isCaseUnlocked(allCases.findIndex(c=>c.id===id))).map(id=>allCases.find(c=>c.id===id))};
renderCharacters=function(){const count=getDiscoveredCharacterCount();app.innerHTML=`<main class="characters-view"><div class="topline"><button data-characters-home>← Agensi</button><span class="tag">FAIL PENDUDUK</span><button data-characters-file>▤ Fail Kes</button></div><header class="characters-heading"><div><div class="eyebrow">DUNIA BAYURAYA</div><h1>Fail Penduduk Bayuraya</h1><p>Kenali penduduk yang pernah ditemui sepanjang penyiasatan.</p></div><div class="characters-count"><span>Watak Ditemui</span><b>${count} / 18</b>${isSecondArcComplete()?'<small>🏆 Fail Kedua Lengkap</small>':isFirstArcComplete()?'<small>🏆 Fail Pertama Lengkap</small>':''}</div></header><div class="characters-layout"><section class="character-gallery">${Object.values(characters).map(characterCard).join('')}</section>${characterDetail(selectedCharacter)}</div><div class="characters-actions"><button data-characters-map class="primary">Peta Bayuraya</button><button data-characters-achievements>Pencapaian</button><button data-characters-home>Kembali ke Agensi</button></div></main>`};

achievementDefinitions.push(
 {id:'A10',icon:'↕',title:'Urutan Tepat',description:'Ikut arahan mengikut urutan yang betul.',unlocked:()=>isHistoricallyComplete('C006')},
 {id:'A11',icon:'◫',title:'Bakul Cermat',description:'Kenal pasti objek menggunakan beberapa penerangan.',unlocked:()=>isHistoricallyComplete('C007')},
 {id:'A12',icon:'▤',title:'Pembaca Rekod',description:'Buat kesimpulan daripada rekod.',unlocked:()=>isHistoricallyComplete('C008')},
 {id:'A13',icon:'✓',title:'Penyaring Fakta',description:'Bezakan maklumat semasa dan relevan.',unlocked:()=>isHistoricallyComplete('C009')},
 {id:'A14',icon:'⌖',title:'Bayuraya Diterokai',description:'Temui semua sepuluh lokasi penting.',unlocked:()=>getExplorationCount()===10},
 {id:'A15',icon:'🏆',title:'Fail Kedua Lengkap',description:'Selesaikan semua kes dalam Fail Kedua.',unlocked:()=>isSecondArcComplete(),hero:true}
);
achievementDefinitions.find(a=>a.id==='A08').unlocked=()=>firstArcCases.every(c=>getBestStars(c.id)>=c.maxStars);
achievementDefinitions.find(a=>a.id==='A09').unlocked=()=>['agency','school','library','mathShop','park','square'].every(id=>getLocationStatus(id)!=='undiscovered');
renderAchievements=function(){const completed=getCompletedCaseCount(),locationsFound=getExplorationCount(),stars=getTotalBestStars(),xp=getTotalBestXP();app.innerHTML=`<main class="achievements-view"><div class="topline"><button data-achievement-home>← Agensi</button><span class="tag">PENCAPAIAN</span><button data-achievement-file>▤ Fail Kes</button></div><header class="achievement-heading"><div><div class="eyebrow">PENCAPAIAN DETEKTIF</div><h1>Jejak Kemajuan Kamu</h1></div>${isSecondArcComplete()?'<div class="achievement-arc">🏆 Fail Kedua Lengkap</div>':isFirstArcComplete()?'<div class="achievement-arc">🏆 Fail Pertama Lengkap</div>':''}</header><section class="detective-summary"><div><span>Kes Selesai</span><b>${completed} / 10</b></div><div><span>Lokasi Ditemui</span><b>${locationsFound} / 10</b></div><div><span>Bintang Terbaik</span><b>${stars} / 40</b></div><div><span>XP terbaik</span><b>${xp}</b></div></section>${[['FAIL PERTAMA',achievementDefinitions.slice(0,9)],['FAIL KEDUA',achievementDefinitions.slice(9)]].map(([name,list])=>`<section><div class="section-heading"><h2>${name}</h2><span>${list.filter(a=>a.unlocked()).length}/${list.length} dicapai</span></div><div class="achievement-grid">${list.map(achievementCard).join('')}</div></section>`).join('')}<section class="records-section"><h2>Prestasi Terbaik</h2><div class="case-record-grid">${allCases.map(c=>{const best=getBestRecord(c.id);return`<article><b>${c.number}</b><span>${c.title}</span><strong>${best?'★'.repeat(best.stars):'Belum selesai'}</strong><small>${best?best.xpEarned+' XP terbaik':''}</small></article>`}).join('')}</div></section></main>`};

const oldRenderTitle=renderTitle;renderTitle=function(){const resume=hasResumableRun(),first=isFirstArcComplete(),second=isSecondArcComplete();app.innerHTML=`<main class="title-screen"><img class="title-background" src="assets/ui/title-bayuraya.webp" alt="Pemandangan bandar Bayuraya yang cerah"><div class="title-shade"></div><section class="title-copy"><p class="title-kicker">AGENSI DETEKTIF BAHASA</p><h1>DETEKTIF <strong>BAHASA</strong></h1><p class="title-tagline">CARI · BACA · SAMBUNG · FIKIR</p>${second?'<p class="title-milestone">🏆 Fail Kedua Lengkap</p>':first?'<p class="title-milestone">🏆 Fail Pertama Lengkap</p>':''}<div class="title-actions">${resume?'<button class="primary title-primary" data-title-resume>SAMBUNG SIASATAN</button><button class="title-secondary" data-title-enter>MASUK AGENSI</button>':'<button class="primary title-primary" data-title-enter>MASUK AGENSI</button>'}</div><p class="title-credit">ZilTeroka · EduGame Percuma MY</p></section><div class="title-klu"><img src="assets/klu.svg" alt="KLU, rakan detektif Bahasa"></div><div class="title-controls"><button data-title-sound>${muted?'♪ Bunyi: Mati':'♪ Bunyi: Hidup'}</button><button data-title-fullscreen>⛶ Skrin Penuh</button><button data-parent-open>Untuk Ibu Bapa</button><small>Tekan dan tahan 2 saat · Enter untuk buka</small></div><p class="title-version">v1.7.0 by Zil-el-Saif</p></main>`};
renderParent=function(){const first=isFirstArcComplete(),second=isSecondArcComplete();app.innerHTML=`<main class="parent-hub"><div class="parent-topline"><button data-parent-close>← Muka Depan</button><span class="tag">UNTUK IBU BAPA</span></div><header class="parent-heading"><div><div class="eyebrow">RUANG IBU BAPA</div><h1>Maklumat & Kemajuan</h1><p>Ruang ringkas untuk memahami permainan dan kemajuan setempat.</p></div>${second?'<div class="parent-arc">🏆 <b>Fail Kedua Lengkap</b></div>':first?'<div class="parent-arc">🏆 <b>Fail Pertama Lengkap</b></div>':''}</header><div class="parent-layout"><div class="parent-information"><section><h2>Tentang Detektif Bahasa</h2><p>Sepuluh kes menggalakkan kanak-kanak membaca, membandingkan maklumat dan membuat kesimpulan.</p></section><section><h2>Kemajuan</h2><div class="parent-stats"><div><span>Kes selesai</span><b>${getCompletedCaseCount()} / 10</b></div><div><span>Lokasi ditemui</span><b>${getExplorationCount()} / 10</b></div><div><span>Watak ditemui</span><b>${getDiscoveredCharacterCount()} / 18</b></div><div><span>Bintang terbaik</span><b>${getTotalBestStars()} / 40</b></div></div></section><section><h2>Simpanan</h2><p>Kemajuan disimpan secara automatik pada peranti dan pelayar ini.</p></section></div><aside class="support-panel"><div class="eyebrow">SOKONG ZILTEROKA</div><h2>Bantu EduGame Percuma</h2><p>Terima kasih kerana membantu kami terus menghasilkan EduGame percuma.</p><img src="assets/support/sokong-detektif-bahasa.png" alt="Poster Sokong Detektif Bahasa dengan kod QR Touch 'n Go eWallet"><small>Imbas menggunakan aplikasi perbankan atau eWallet.</small></aside></div></main>`};
resetDetektifProgress=function(){const keepMuted=muted;cases={C001:{run:fresh1(),record:null},C002:{run:fresh2(),record:null},C003:{run:fresh3(),record:null},C004:{run:fresh4(),record:null},C005:{run:fresh5(),record:null},C006:{run:fresh6(),record:null},C007:{run:fresh7(),record:null},C008:{run:fresh8(),record:null},C009:{run:fresh9(),record:null},C010:{run:fresh10(),record:null}};activeCase='C001';state=cases.C001.run;record=null;clues=clues1;muted=keepMuted;home=true;file=false;feedback='';wrong=false;closeWorldViews();resetConfirm=false;parentOpen=false;titleOpen=true;persist();render()};

const renderBeforeV13=render;render=function(){if(!isSecondArcCase(activeCase)||titleOpen||parentOpen||mapOpen||achievementsOpen||charactersOpen||guideOpen){renderBeforeV13();return}document.querySelector('#sound').textContent=muted?'♪ Bunyi: Mati':'♪ Bunyi: Hidup';if(home){app.innerHTML=homeView();return}renderSecondCase()};
app.addEventListener('click',e=>{if(!isSecondArcCase(activeCase)||titleOpen||parentOpen||mapOpen||achievementsOpen||charactersOpen||guideOpen)return;const b=e.target.closest('button');if(!b||b.disabled||b.dataset.case)return;e.stopImmediatePropagation();sound('ui-click');handleSecondClick(b)},true);

// Update guide copy and visible release string without changing its structure.
guideSections[4].body=guideSections[4].body.replace('melihat tempat, kemajuan dan penduduk','melihat lokasi, dua fail kes, kemajuan dan penduduk').replace('Peta Bayuraya','Peta Bayuraya · 10 lokasi');
document.querySelector('footer span:last-child').textContent='v1.7.0 by Zil-el-Saif';
render();
