// v1.6.0 Third Arc — C011–C012 content using the existing scene, record and mechanics systems.
const thirdArcClues={C011:[
 'Papan Jejak Rahsia berada berhampiran jam besar.',
 'Ayyash nampak bangku panjang di sebelah papan itu.',
 'Papan itu bukan berhampiran kaunter tiket.',
 'Peta stesen menunjukkan hanya Platform 2 mempunyai jam besar dan bangku panjang bersebelahan.',
 'Jalur tulisan daripada papan Jejak Rahsia ditemui di belakang papan tanda Platform 2.'
],C012:[
 'Struktur itu dibina merentasi Sungai Bayuraya.',
 'Struktur itu digunakan oleh pejalan kaki dan penunggang basikal.',
 'Bahan utama struktur itu ialah kayu.',
 'Struktur itu tidak lagi digunakan selepas jambatan baharu siap.',
 'Foto arkib menunjukkan struktur yang sama dengan model pameran.'
]};
const thirdArcCases=[
 {id:'C011',number:'KES 011',title:'Misteri Simbol di Papan Tanda',difficulty:'⭐⭐⭐⭐ Jejak Teka',location:'Stesen Bas Bayuraya',scene:'busStation',character:'Ayyash',portrait:'assets/characters/ayyash.webp',maxStars:4,maxXP:330},
 {id:'C012',number:'KES 012',title:'Misteri Label Pameran',difficulty:'⭐⭐⭐⭐ Jejak Fakta',location:'Galeri Warisan Bayuraya',scene:'heritageGallery',character:'Affan',portrait:'assets/characters/affan.webp',maxStars:4,maxXP:350}
];
const fresh11=()=>({caseId:'C011',status:'in_progress',scene:0,cluesFound:0,hintsUsed:0,attempts:0,stars:0,xpEarned:0,completedAt:null,solved:{},hintLevels:{},errors:{},objects:[],sceneProgress:{busStation:[]},links:['','','']});
const fresh12=()=>({caseId:'C012',status:'in_progress',scene:0,cluesFound:0,hintsUsed:0,attempts:0,stars:0,xpEarned:0,completedAt:null,solved:{},hintLevels:{},errors:{},objects:[],sceneProgress:{heritageGallery:[]},links:['','','']});
cases.C011??={run:fresh11(),record:null};
cases.C011.run={...fresh11(),...cases.C011.run,sceneProgress:{busStation:[...(cases.C011.run?.sceneProgress?.busStation||[])]},links:[...(cases.C011.run?.links||['','',''])]};
cases.C012??={run:fresh12(),record:null};
cases.C012.run={...fresh12(),...cases.C012.run,sceneProgress:{heritageGallery:[...(cases.C012.run?.sceneProgress?.heritageGallery||[])]},links:[...(cases.C012.run?.links||['','',''])]};
allCases.push(...thirdArcCases);
if(saved?.activeCase==='C011'||saved?.activeCase==='C012'){activeCase=saved.activeCase;state=cases[activeCase].run;record=cases[activeCase].record||null;clues=thirdArcClues[activeCase]}
const isThirdArcCase=id=>id==='C011'||id==='C012';
const investigationMechanics=globalThis.DetektifMechanics||window.DetektifMechanics;

scenes.busStation={id:'stesen-bas-bayuraya',image:'assets/locations/stesen-bas-bayuraya.webp',alt:'Stesen Bas Bayuraya yang cerah dengan kaunter tiket, jam besar, bangku panjang, papan jadual dan tiga platform',aspectRatio:'16 / 9',place:'Stesen Bas Bayuraya',hotspots:[
 {id:'kaunter tiket',label:'Kaunter tiket',x:1,y:25,w:20,h:45},{id:'platform 1',label:'Platform 1',x:25,y:27,w:9,h:22},{id:'platform 2',label:'Platform 2',x:42,y:20,w:10,h:24},{id:'platform 3',label:'Platform 3',x:88,y:12,w:10,h:26},{id:'jam besar',label:'Jam besar',x:61,y:14,w:9,h:22},{id:'papan jadual',label:'Papan jadual stesen',x:72,y:33,w:12,h:25},{id:'bangku panjang',label:'Bangku panjang',x:72,y:58,w:20,h:20},{id:'tong sampah',label:'Tong sampah',x:57,y:57,w:8,h:20},{id:'jalur tulisan',label:'Jalur tulisan di belakang papan tanda Platform 2',x:48,y:46,w:8,h:10}
]};
scenes.heritageGallery={id:'galeri-warisan-bayuraya',image:'assets/locations/galeri-warisan-bayuraya.webp',alt:'Galeri Warisan Bayuraya yang cerah dengan model jambatan kayu, kad maklumat, foto arkib, label pameran, meja dan papan maklumat',aspectRatio:'16 / 9',place:'Galeri Warisan Bayuraya',hotspots:[
 {id:'model pameran',label:'Model jambatan kayu',x:26,y:49,w:38,h:30},{id:'kad maklumat',label:'Kad maklumat pameran',x:64,y:62,w:9,h:22},{id:'foto arkib',label:'Foto arkib jambatan lama',x:7,y:8,w:25,h:38},{id:'label a',label:'Label pameran A',x:5,y:46,w:9,h:20},{id:'label b',label:'Label pameran B',x:66,y:43,w:9,h:18},{id:'label c',label:'Label pameran C',x:87,y:48,w:11,h:22},{id:'meja maklumat',label:'Meja maklumat galeri',x:78,y:30,w:21,h:18},{id:'papan maklumat',label:'Papan maklumat galeri',x:60,y:18,w:18,h:24}
]};
const c011Riddles={
 1:{title:'Apakah benda itu?',prompt:'Saya ada nombor tetapi bukan buku. Orang melihat saya untuk mengetahui waktu. Apakah saya?',choices:['Jam besar','Bangku panjang','Papan jadual','Tong sampah'],answer:0,hints:['Cari benda yang digunakan untuk melihat waktu.','Perhatikan benda bulat berhampiran kawasan menunggu.','Jam besar ialah petunjuk penting.']},
 2:{title:'Apakah yang Ayyash nampak?',prompt:'Saya panjang tetapi bukan jalan. Orang duduk di atas saya sambil menunggu.',choices:['Kaunter tiket','Bangku panjang','Papan jadual','Tong sampah'],answer:1,hints:['Cari tempat orang duduk semasa menunggu.','Benda ini berada di kawasan menunggu.','Pilih bangku panjang.']},
 3:{title:'Di manakah papan itu tidak berada?',prompt:'Ayyash melihat jam dan bangku di sebelah papan. Dia tidak melihat tempat membeli tiket. Kawasan manakah perlu disingkirkan?',choices:['Platform','Kawasan jam','Kaunter tiket','Bangku panjang'],answer:2,hints:['Cari tempat orang membeli tiket.','Petunjuk menyebut papan itu bukan berhampiran tempat membeli tiket.','Singkirkan kaunter tiket.']}
};
const c011Tasks={4:{title:'Semak peta stesen.',prompt:'Hanya satu platform mempunyai jam besar dan bangku panjang bersebelahan. Platform manakah itu?',choices:['Platform 1','Platform 2','Platform 3'],answer:1},5:{type:'scene',target:'jalur tulisan',title:'Cari kesan terakhir.',prompt:'Cari jalur tulisan di belakang papan tanda Platform 2.'}};
const c011Evidence=['berada berhampiran','berada di','ditemui di belakang'];
const c011Task=()=>state.scene<=3?c011Riddles[state.scene]:c011Tasks[state.scene];
function c011Hint(){const key=`C011-${state.scene}`,next=Math.min(3,(state.hintLevels[key]||0)+1);if(next>(state.hintLevels[key]||0))state.hintsUsed++;state.hintLevels[key]=next;const task=c011Task(),fallback=['Baca semua maklumat sekali lagi.','Bandingkan tempat dan objek berdekatan.','Pilih jawapan yang sepadan dengan semua bukti.'];feedback=`Bantuan ${next}/3: ${(task.hints||fallback)[next-1]}`;wrong=false;sound('hint');persist();render()}
function completeC011Clue(){state.solved[state.scene]=true;state.cluesFound=Math.max(state.cluesFound,state.scene);feedback=`✓ Petunjuk ${state.scene}/5 ditemui.`;wrong=false;sound('clue-found');persist();render()}
function c011Riddle(task,done){const mechanicState={hints:state.hintLevels[`C011-${state.scene}`]||0,feedback:done?'✓ Tepat! Petunjuk ini membantu menentukan lokasi papan.':''};return `${renderScene(scenes.busStation,null,true,state.sceneProgress.busStation)}<div class="ayyash-context"><img src="assets/characters/ayyash.webp" alt="Potret Ayyash"><p><b>Ayyash mengingat beberapa tanda di sekitar papan.</b> Gunakan ingatannya untuk menyelesaikan teka-teki.</p></div>${investigationMechanics.renderRiddleTask(task,mechanicState)}${done?`<div class="evidence"><small>PETUNJUK ${state.scene} DITEMUI</small>${thirdArcClues.C011[state.scene-1]}</div>${button('Teruskan →','next','primary')}`:''}`}
function renderC011Task(task,done){if(state.scene<=3)return c011Riddle(task,done);if(task.type==='scene')return `<h2>${task.title}</h2><p>${task.prompt}</p>${renderScene(scenes.busStation,task.target,done,state.sceneProgress.busStation)}${done?`<div class="evidence"><small>PETUNJUK 5 DITEMUI</small>${thirdArcClues.C011[4]}</div>${button('Susun bukti →','next','primary')}`:''}`;return `<h2>${task.title}</h2><p>${task.prompt}</p><div class="station-platforms" aria-label="Maklumat platform"><article><b>PLATFORM 1</b><span>Papan jadual</span></article><article><b>PLATFORM 2</b><span>Jam besar · Bangku panjang</span></article><article><b>PLATFORM 3</b><span>Kaunter tiket</span></article></div><div class="choices vertical statement-options">${task.choices.map((o,i)=>`<button data-third-answer="${i}" ${done?'disabled':''} class="statement-option ${done&&i===task.answer?'selected':''}"><span class="option-label" aria-hidden="true">${'ABC'[i]}</span><span class="option-text">${o}</span></button>`).join('')}</div>${done?`<div class="evidence"><small>PETUNJUK 4 DITEMUI</small>${thirdArcClues.C011[3]}</div>${button('Teruskan →','next','primary')}`:''}`}
function renderC011Evidence(done){const labels=[['JAM BESAR','PLATFORM 2'],['BANGKU PANJANG','PLATFORM 2'],['JALUR TULISAN','PAPAN PLATFORM 2']];return `<h2>Sambungkan bukti.</h2><div class="connections">${labels.map(([a,b],i)=>`<div class="connection"><b>${a}</b><select data-third-link="${i}" aria-label="Hubungan ${a} kepada ${b}" ${done?'disabled':''}><option value="">Pilih hubungan…</option><option ${state.links[i]===c011Evidence[i]?'selected':''}>${c011Evidence[i]}</option><option>tidak berkaitan</option></select><b>${b}</b></div>`).join('')}</div>${button(done?'Buat deduksi →':'Semak sambungan',done?'next':'third-check','primary')}`}
function renderC011Deduction(){return `<h2>Di manakah lokasi asal papan Jejak Rahsia?</h2><p>Gunakan jam besar, bangku panjang dan jalur tulisan.</p><div class="choices vertical statement-options">${['Berhampiran Platform 1.','Berhampiran kaunter tiket.','Berhampiran Platform 2.','Berhampiran Platform 3.'].map((o,i)=>`<button data-third-theory="${i}" class="statement-option"><span class="option-label" aria-hidden="true">${'ABCD'[i]}</span><span class="option-text">${o}</span></button>`).join('')}</div>`}
function completeC011(){state.status='completed';state.stars=Math.max(1,4-Math.floor(state.hintsUsed/3));state.xpEarned=state.hintsUsed?300:330;state.completedAt=new Date().toISOString();if(!record||state.xpEarned>record.xpEarned||(state.xpEarned===record.xpEarned&&state.stars>record.stars))record=JSON.parse(JSON.stringify(state));state.scene=8;sound('case-complete');persist();render()}
function renderC011Result(){const best=record||cases.C011.record||state;return `<div class="celebrate result-screen"><div class="tag">KES 011 SELESAI</div><h2>Misteri Simbol di Papan Tanda</h2><div class="stars" aria-label="${state.stars} daripada 4 bintang">${'★'.repeat(state.stars)}${'☆'.repeat(4-state.stars)}</div><div class="stats"><div><b>5/5</b><span>Petunjuk</span></div><div><b>+${state.xpEarned}</b><span>XP diperoleh</span></div><div><b>${best.xpEarned||0}</b><span>XP terbaik</span></div></div><section class="milestone"><h3>✦ FAIL KETIGA DIBUKA</h3><p>Jejak Rahsia Bayuraya telah bermula.</p></section><div class="actions">${button('Lihat Fail Kes','file','primary')}${button('Kembali ke agensi','home')}${button('Main semula','replay')}</div></div>`}
function renderC011(){const s=state.scene,done=state.solved[s];let body;if(file)body=`<h2>Fail Kes · Misteri Simbol di Papan Tanda</h2>${thirdArcClues.C011.slice(0,state.cluesFound).map((c,i)=>`<div class="evidence"><small>PETUNJUK ${i+1}</small>${c}</div>`).join('')}${button('Kembali','closefile','primary')}`;else if(s===0)body=`<div class="eyebrow">KES 011 · FAIL KETIGA</div><h2>Misteri Simbol di Papan Tanda</h2><div class="letter"><p>Aktiviti Jejak Rahsia Bayuraya akan bermula di Stesen Bas Bayuraya.</p><p>Papan sementara telah dialihkan ketika kawasan dibersihkan. Ayyash masih mengingati beberapa tanda di lokasi asalnya.</p></div><div class="aynaa-card"><img src="assets/characters/ayyash.webp" alt="Potret Ayyash" width="62" height="72"><span><b>Ayyash</b>Stesen Bas Bayuraya</span></div>${button('Mulakan siasatan →','next','primary')}`;else if(s<=5)body=renderC011Task(c011Task(),done);else if(s===6)body=renderC011Evidence(done);else if(s===7)body=renderC011Deduction();else if(s===8)body=`<div class="celebrate"><div class="eyebrow">✧ KES SELESAI!</div><h2>Papan itu berada berhampiran Platform 2.</h2><p>Jam besar, bangku panjang dan jalur tulisan semuanya menunjukkan Platform 2. Papan itu hanya dialihkan semasa kerja pembersihan.</p>${button('Lihat keputusan →','next','primary')}</div>`;else body=renderC011Result();app.innerHTML=`<main><div class="topline">${button('← Agensi','home')}<span class="tag">KES 011 · ${state.cluesFound}/5 PETUNJUK</span>${button('▤ Fail Kes','file')}</div><div class="layout"><section class="panel">${body}${feedback?`<div role="status" class="feedback ${wrong?'wrong':''}">${feedback}</div>`:''}</section><aside class="klu">${companionArt(state.status==='completed'||s>=8?'celebrate':wrong?'thinking':feedback.startsWith('Bantuan')?'hint':done?'excited':'neutral')}<div class="klu-message"><div class="eyebrow">KLU · RAKAN DETEKTIF</div><p>${s===6?'Sambungkan tiga hubungan yang disokong bukti.':s===7?'Pilih lokasi yang sepadan dengan semua lima petunjuk.':'Teka-teki ini membawa kita lebih dekat kepada papan itu.'}</p>${s>=4&&s<=5&&!done?button('☀ Bantuan '+(state.hintLevels[`C011-${s}`]||0)+'/3','hint'):''}</div></aside>${caseShelf()}</div></main>`}
function handleC011Click(b){const task=c011Task();if(b.hasAttribute?.('data-mechanic-hint')){c011Hint();return}if(b.dataset.riddleAnswer!==undefined){if(state.solved[state.scene])return;state.attempts++;if(Number(b.dataset.riddleAnswer)===task.answer)completeC011Clue();else fail('Belum tepat. Fikirkan fungsi benda itu dan cuba lagi.');return}if(b.dataset.thirdAnswer!==undefined){if(state.solved[state.scene])return;state.attempts++;if(Number(b.dataset.thirdAnswer)===task.answer)completeC011Clue();else fail('Belum tepat. Bandingkan ketiga-tiga platform.');return}if(b.dataset.object){state.attempts++;if(state.scene===5&&b.dataset.object==='jalur tulisan'){if(!state.sceneProgress.busStation.includes('jalur tulisan'))state.sceneProgress.busStation.push('jalur tulisan');completeC011Clue()}else fail('Objek itu belum melengkapkan petunjuk ini. Cuba lagi.');return}if(b.dataset.thirdTheory!==undefined){state.attempts++;if(b.dataset.thirdTheory==='2'&&state.cluesFound===5&&state.solved[6])completeC011();else fail('Teori itu belum menerangkan semua petunjuk. Cuba lagi.');return}switch(b.dataset.action){case'start':home=false;file=false;render();break;case'home':home=true;file=false;persist();render();break;case'file':file=true;render();break;case'closefile':file=false;render();break;case'next':if(state.scene>=1&&state.scene<=6&&!state.solved[state.scene])return;state.scene++;feedback='';wrong=false;persist();render();break;case'hint':c011Hint();break;case'third-check':state.attempts++;if(state.cluesFound===5&&state.links.every((v,i)=>v===c011Evidence[i])){state.solved[6]=true;feedback='✓ Semua bukti disambungkan dengan tepat.';wrong=false;sound('board-complete');persist();render()}else fail('Sambungan belum lengkap. Semak hubungan setiap bukti.');break;case'replay':state=fresh11();record=cases.C011.record||record;home=false;file=false;feedback='';wrong=false;persist();render();break}}

const c012Trivia={
 1:{question:'Apakah fungsi utama struktur ini?',source:'Kad maklumat: Struktur ini dibina merentasi Sungai Bayuraya untuk menghubungkan dua bahagian bandar.',choices:['Menyeberangi sungai','Menyimpan hasil kebun','Menunjukkan waktu'],answer:0,hints:['Cari kata yang menerangkan kedudukan struktur.','Struktur itu merentasi Sungai Bayuraya.','Pilih fungsi untuk menyeberangi sungai.']},
 3:{question:'Penerangan manakah sepadan dengan model pameran?',source:'Catatan bahan: Bahan utama struktur ini ialah kayu.',choices:['Struktur batu','Struktur kayu','Struktur logam'],answer:1,hints:['Baca bahan utama pada catatan.','Perhatikan perkataan “kayu”.','Pilih struktur kayu.']},
 4:{question:'Mengapakah struktur lama itu tidak lagi digunakan?',source:'Catatan sejarah: Struktur lama ditutup selepas jambatan baharu siap dibina.',choices:['Jambatan baharu telah siap','Sungai telah kering','Model itu terlalu kecil'],answer:0,hints:['Cari peristiwa yang berlaku selepas struktur lama digunakan.','Catatan menyebut jambatan baharu.','Pilih jawapan tentang jambatan baharu yang siap.']}
};
const c012Evidence=['dibuat daripada','digunakan untuk','sepadan dengan'];
function c012Hint(){const key=`C012-${state.scene}`,next=Math.min(3,(state.hintLevels[key]||0)+1);if(next>(state.hintLevels[key]||0))state.hintsUsed++;state.hintLevels[key]=next;const task=c012Trivia[state.scene],fallback=state.scene===2?['Baca kenyataan Affan.','Cari siapa yang menggunakan struktur itu.','Catat pejalan kaki dan penunggang basikal.']:['Perhatikan foto lama.','Bandingkan bentuk jambatan dalam foto dan model.','Pilih foto arkib jambatan lama.'];feedback=`Bantuan ${next}/3: ${(task?.hints||fallback)[next-1]}`;wrong=false;sound('hint');persist();render()}
function completeC012Clue(){state.solved[state.scene]=true;state.cluesFound=Math.max(state.cluesFound,state.scene);feedback=`✓ Petunjuk ${state.scene}/5 ditemui.`;wrong=false;sound('clue-found');persist();render()}
function c012TriviaView(task,done){const mechanicState={hints:state.hintLevels[`C012-${state.scene}`]||0,feedback:done?'✓ Tepat! Fakta pada sumber menyokong jawapan itu.':''};return `${renderScene(scenes.heritageGallery,null,true,state.sceneProgress.heritageGallery)}${investigationMechanics.renderInvestigationTrivia(task,mechanicState)}${done?`<div class="evidence"><small>PETUNJUK ${state.scene} DITEMUI</small>${thirdArcClues.C012[state.scene-1]}</div>${button('Teruskan →','next','primary')}`:''}`}
function c012Affan(done){return `<h2>Dengar penerangan Affan.</h2><div class="heritage-witness"><img src="assets/characters/affan.webp" alt="Potret Affan"><div><div class="eyebrow">AFFAN · PELAWAT GALERI</div><blockquote>“Kad ini menyatakan struktur itu digunakan oleh pejalan kaki dan penunggang basikal. Foto arkib di sana mungkin membantu kita.”</blockquote></div></div>${done?`<div class="evidence"><small>PETUNJUK 2 DITEMUI</small>${thirdArcClues.C012[1]}</div>${button('Teruskan →','next','primary')}`:button('Catat kenyataan Affan','c012-affan','primary')}`}
function c012Photo(done){return `<div class="scene-heading"><div><span class="scene-memory">GALERI WARISAN BAYURAYA</span><h2>Bandingkan foto dengan model.</h2></div><span class="scene-step">PETUNJUK 5/5</span></div><p class="scene-instruction">Cari foto arkib yang menunjukkan struktur yang sama dengan model pameran.</p>${renderScene(scenes.heritageGallery,'foto arkib',done,state.sceneProgress.heritageGallery)}${done?`<div class="evidence"><small>PETUNJUK 5 DITEMUI</small>${thirdArcClues.C012[4]}</div>${button('Susun bukti →','next','primary')}`:''}`}
function renderC012Evidence(done){const labels=[['MODEL PAMERAN','KAYU'],['MODEL PAMERAN','MENYEBERANGI SUNGAI'],['FOTO ARKIB','MODEL PAMERAN']];return `<h2>Sambungkan bukti.</h2><p>Gunakan fakta pada kad, catatan sejarah dan foto arkib.</p><div class="connections">${labels.map(([a,b],i)=>`<div class="connection"><b>${a}</b><select data-c012-link="${i}" aria-label="Hubungan ${a} kepada ${b}" ${done?'disabled':''}><option value="">Pilih hubungan…</option><option ${state.links[i]===c012Evidence[i]?'selected':''}>${c012Evidence[i]}</option><option>tidak berkaitan</option></select><b>${b}</b></div>`).join('')}</div>${button(done?'Buat deduksi →':'Semak sambungan',done?'next':'c012-check','primary')}`}
function renderC012Deduction(){return `<h2>Label manakah yang sepatutnya diletakkan pada model?</h2><p>Gunakan lokasi, pengguna, bahan, sejarah dan foto arkib.</p><div class="choices vertical statement-options">${['Jambatan Kayu Lama Bayuraya','Menara Jam Lama','Perahu Sungai Bayuraya'].map((o,i)=>`<button data-c012-theory="${i}" class="statement-option"><span class="option-label" aria-hidden="true">${'ABC'[i]}</span><span class="option-text">${o}</span></button>`).join('')}</div>`}
function completeC012(){state.status='completed';state.stars=Math.max(1,4-Math.floor(state.hintsUsed/3));state.xpEarned=state.hintsUsed?320:350;state.completedAt=new Date().toISOString();if(!record||state.xpEarned>record.xpEarned||(state.xpEarned===record.xpEarned&&state.stars>record.stars))record=JSON.parse(JSON.stringify(state));state.scene=8;sound('case-complete');persist();render()}
function renderC012Result(){const best=record||cases.C012.record||state;return `<div class="celebrate result-screen"><div class="tag">KES 012 SELESAI</div><h2>Misteri Label Pameran</h2><div class="stars" aria-label="${state.stars} daripada 4 bintang">${'★'.repeat(state.stars)}${'☆'.repeat(4-state.stars)}</div><div class="stats"><div><b>5/5</b><span>Petunjuk</span></div><div><b>+${state.xpEarned}</b><span>XP diperoleh</span></div><div><b>${best.xpEarned||0}</b><span>XP terbaik</span></div></div><section class="milestone"><h3>✦ PEMBACA FAKTA</h3><p>Kamu menggunakan fakta pameran untuk memulihkan label yang betul.</p></section><div class="actions">${button('Lihat Fail Kes','file','primary')}${button('Kembali ke agensi','home')}${button('Main semula','replay')}</div></div>`}
function renderC012(){const s=state.scene,done=state.solved[s];let body;if(file)body=`<h2>Fail Kes · Misteri Label Pameran</h2>${thirdArcClues.C012.slice(0,state.cluesFound).map((c,i)=>`<div class="evidence"><small>PETUNJUK ${i+1}</small>${c}</div>`).join('')}${button('Kembali','closefile','primary')}`;else if(s===0)body=`<div class="eyebrow">KES 012 · FAIL KETIGA</div><h2>Misteri Label Pameran</h2><div class="letter"><p>Cikgu Farah mendapati tiga label pameran telah bercampur semasa ruang galeri dikemas.</p><p>Tiada benda dicuri. Baca sumber galeri dan tentukan label yang betul untuk model itu.</p></div><div class="heritage-witness compact"><img src="assets/characters/cikgu-farah.webp" alt="Potret Cikgu Farah"><span><b>Cikgu Farah</b>Galeri Warisan Bayuraya</span></div>${button('Mulakan siasatan →','next','primary')}`;else if(c012Trivia[s])body=c012TriviaView(c012Trivia[s],done);else if(s===2)body=c012Affan(done);else if(s===5)body=c012Photo(done);else if(s===6)body=renderC012Evidence(done);else if(s===7)body=renderC012Deduction();else if(s===8)body=`<div class="celebrate"><div class="eyebrow">✧ KES SELESAI!</div><h2>Label yang betul ialah Jambatan Kayu Lama Bayuraya.</h2><p>Fakta tentang sungai, pengguna, bahan kayu, sejarah dan foto arkib semuanya sepadan dengan model itu.</p>${button('Lihat keputusan →','next','primary')}</div>`;else body=renderC012Result();app.innerHTML=`<main><div class="topline">${button('← Agensi','home')}<span class="tag">KES 012 · ${state.cluesFound}/5 PETUNJUK</span>${button('▤ Fail Kes','file')}</div><div class="layout"><section class="panel">${body}${feedback?`<div role="status" class="feedback ${wrong?'wrong':''}">${feedback}</div>`:''}</section><aside class="klu">${companionArt(state.status==='completed'||s>=8?'celebrate':wrong?'thinking':feedback.startsWith('Bantuan')?'hint':done?'excited':'neutral')}<div class="klu-message"><div class="eyebrow">KLU · RAKAN DETEKTIF</div><p>${s===6?'Sambungkan hanya hubungan yang disokong oleh fakta.':s===7?'Pilih label yang sepadan dengan kelima-lima petunjuk.':'Baca sumber, cari fakta dan bandingkan bukti.'}</p>${(s===2||s===5)&&!done?button('☀ Bantuan '+(state.hintLevels[`C012-${s}`]||0)+'/3','hint'):''}</div></aside>${caseShelf()}</div></main>`}
function handleC012Click(b){const task=c012Trivia[state.scene];if(b.hasAttribute?.('data-mechanic-hint')){c012Hint();return}if(b.dataset.triviaAnswer!==undefined){if(state.solved[state.scene])return;state.attempts++;if(Number(b.dataset.triviaAnswer)===task.answer)completeC012Clue();else fail('Belum tepat. Baca sumber pameran dan cuba lagi.');return}if(b.dataset.object){state.attempts++;if(state.scene===5&&b.dataset.object==='foto arkib'){if(!state.sceneProgress.heritageGallery.includes('foto arkib'))state.sceneProgress.heritageGallery.push('foto arkib');completeC012Clue()}else fail('Objek itu belum melengkapkan petunjuk ini. Cuba lagi.');return}if(b.dataset.c012Theory!==undefined){state.attempts++;if(b.dataset.c012Theory==='0'&&state.cluesFound===5&&state.solved[6])completeC012();else fail('Label itu belum sepadan dengan semua fakta. Cuba lagi.');return}switch(b.dataset.action){case'start':home=false;file=false;render();break;case'home':home=true;file=false;persist();render();break;case'file':file=true;render();break;case'closefile':file=false;render();break;case'next':if(state.scene>=1&&state.scene<=6&&!state.solved[state.scene])return;state.scene++;feedback='';wrong=false;persist();render();break;case'hint':c012Hint();break;case'c012-affan':state.attempts++;completeC012Clue();break;case'c012-check':state.attempts++;if(state.cluesFound===5&&state.links.every((v,i)=>v===c012Evidence[i])){state.solved[6]=true;feedback='✓ Semua bukti disambungkan dengan tepat.';wrong=false;sound('board-complete');persist();render()}else fail('Sambungan belum lengkap. Semak hubungan setiap bukti.');break;case'replay':state=fresh12();record=cases.C012.record||record;home=false;file=false;feedback='';wrong=false;persist();render();break}}

const unlockedBeforeC011=isCaseUnlocked;isCaseUnlocked=function(index){if(index===10)return isHistoricallyComplete('C010');if(index===11)return isHistoricallyComplete('C011');return unlockedBeforeC011(index)};
const switchBeforeC011=switchCase;switchCase=function(id){if(!isThirdArcCase(id)){switchBeforeC011(id);return}const index=id==='C011'?10:11;if(!isCaseUnlocked(index))return;persist();activeCase=id;state=cases[id].run;record=cases[id].record||null;clues=thirdArcClues[id];home=true;file=false;feedback='';wrong=false;persist();render()};
getMaximumStars=function(){return 48};hasMaximumRecords=function(){return allCases.every(c=>getBestStars(c.id)>=c.maxStars)};
const shelfBeforeC011=caseShelf;caseShelf=function(){const html=shelfBeforeC011(),cards=thirdArcCases.map((c,i)=>{const index=10+i,open=isCaseUnlocked(index),status=getCaseStatus(c.id,index);return`<button class="case-card ${activeCase===c.id?'active':''} case-${status}" data-case="${c.id}" ${open?'':'disabled'} aria-label="${open?`${c.number}, ${c.title}`:`${c.number}, terkunci`}">${open?`<img class="case-thumb" src="${i?'assets/locations/galeri-warisan-bayuraya.webp':'assets/locations/stesen-bas-bayuraya.webp'}" alt="" aria-hidden="true">`:'<svg class="icon" aria-hidden="true"><use href="#i-lock"/></svg>'}<span><strong>${c.number}</strong>${open?c.title:'???'}<small>${open?c.difficulty:`Selesaikan KES ${String(10+i).padStart(3,'0')}`}</small>${caseStatusText(c.id,index)}</span></button>`}).join('');const card=`<div class="case-arc-heading"><b>FAIL KETIGA</b><span>${thirdArcCases.filter(c=>isHistoricallyComplete(c.id)).length}/2</span></div><div class="case-arc-subtitle">Jejak Rahsia Bayuraya</div><div class="case-list">${cards}</div>`;return html.replace('</div></aside>',card+'</div></aside>')};
const homeBeforeC011=homeView;homeView=function(){if(!isThirdArcCase(activeCase))return homeBeforeC011();const c=thirdArcCases.find(item=>item.id===activeCase),is12=activeCase==='C012',start=state.status==='completed'?'Lihat Keputusan':state.scene>0?'Sambung Siasatan':'Mula Siasatan',image=is12?'assets/locations/galeri-warisan-bayuraya.webp':'assets/locations/stesen-bas-bayuraya.webp',copy=is12?'Baca sumber pameran, cari fakta dan pulihkan label yang betul pada model warisan.':'Gunakan ingatan Ayyash, objek stesen dan teka-teki untuk mencari lokasi asal papan Jejak Rahsia.',klu=is12?'Fakta yang tepat akan membantu kita memilih label yang betul.':'Teka-teki akan membantu kita memahami lokasi papan.';return `<main><div class="welcome-line">SELAMAT DATANG KE BAYURAYA · FAIL KETIGA</div><div class="landing-layout"><section class="case-hero"><span class="file-tab">${c.number}</span><h1>${c.title}</h1><div class="case-overview"><div><span class="difficulty">${c.difficulty}</span><p>${copy}</p></div><figure class="evidence-photo"><img class="case-thumb" src="${image}" alt="${c.location}"><figcaption>${c.location}</figcaption></figure></div>${button(start,'start','primary')}<p class="meta">Tiada had masa · Kemajuan disimpan</p>${record?`<p class="meta">★ Rekod terbaik: ${record.stars} bintang · ${record.xpEarned} XP</p>`:''}</section><aside class="klu">${companionArt(state.status==='completed'?'celebrate':'neutral')}<div class="klu-message"><div class="eyebrow">KLU · RAKAN DETEKTIF</div><p>${klu}</p></div></aside>${caseShelf()}</div></main>`};
locations.station={id:'station',label:'Stesen Bas Bayuraya',x:88,y:57,w:10,h:12,relatedCases:['C011'],description:'Stesen bas kecil yang menjadi salah satu titik Jejak Rahsia Bayuraya.'};
locations.gallery={id:'gallery',label:'Galeri Warisan Bayuraya',x:31,y:8,w:8,h:13,relatedCases:['C012'],description:'Galeri moden yang menyimpan model, foto arkib dan fakta sejarah Bayuraya.'};
const statusBeforeC011=getLocationStatus;getLocationStatus=function(id){if(id==='station')return isHistoricallyComplete('C011')?'investigated':isCaseUnlocked(10)||hasCaseStarted('C011')?'discovered':'undiscovered';if(id==='gallery')return isHistoricallyComplete('C012')?'investigated':hasCaseStarted('C012')||isCaseUnlocked(11)?'discovered':'undiscovered';return statusBeforeC011(id)};
characters.ayyash={id:'ayyash',name:'Ayyash',role:'Penduduk Bayuraya',portrait:'assets/characters/ayyash.webp',relatedCases:['C011'],relatedLocations:['station'],shortBio:'Membantu mengingati tanda tempat di Stesen Bas Bayuraya semasa Jejak Rahsia Bayuraya.'};
characters.affan={id:'affan',name:'Affan',role:'Pelawat galeri',portrait:'assets/characters/affan.webp',relatedCases:['C012'],relatedLocations:['gallery'],shortBio:'Membaca fakta pameran dan menunjukkan foto arkib yang membantu siasatan di Galeri Warisan Bayuraya.'};
const discoveredBeforeC011=isCharacterDiscovered;isCharacterDiscovered=function(id){if(id==='ayyash')return hasCaseStarted('C011');if(id==='affan')return hasCaseStarted('C012');return discoveredBeforeC011(id)};
achievementDefinitions.push({id:'A16',icon:'assets/achievements/a16.webp',title:'Pemecah Teka',description:'Selesaikan Misteri Simbol di Papan Tanda.',unlocked:()=>isHistoricallyComplete('C011')},{id:'A17',icon:'assets/achievements/a17.webp',title:'Pembaca Fakta',description:'Selesaikan Misteri Label Pameran.',unlocked:()=>isHistoricallyComplete('C012')});
achievementDefinitions.find(a=>a.id==='A14').unlocked=()=>getExplorationCount()>=10;
const mapBeforeC011=renderMap;renderMap=function(){mapBeforeC011();app.innerHTML=app.innerHTML.replace(/Bayuraya Diterokai<\/span><b>(\d+)\/10/g,'Bayuraya Diterokai</span><b>$1/12').replace(/daripada 10 lokasi penting/g,'daripada 12 lokasi penting')};
const charactersBeforeC011=renderCharacters;renderCharacters=function(){charactersBeforeC011();app.innerHTML=app.innerHTML.replace(/Watak Ditemui<\/span><b>(\d+) \/ 18/g,'Watak Ditemui</span><b>$1 / 20').replace(/daripada 18 watak/g,'daripada 20 watak')};
const achievementsBeforeC011=renderAchievements;renderAchievements=function(){const thirdBadges=achievementDefinitions.splice(15);achievementsBeforeC011();achievementDefinitions.push(...thirdBadges);app.innerHTML=app.innerHTML.replace(/Kes Selesai<\/span><b>(\d+) \/ 10/g,'Kes Selesai</span><b>$1 / 12').replace(/Lokasi Ditemui<\/span><b>(\d+) \/ 10/g,'Lokasi Ditemui</span><b>$1 / 12').replace(/Bintang Terbaik<\/span><b>(\d+) \/ 40/g,'Bintang Terbaik</span><b>$1 / 48').replace('</section><section class="records-section">',`</section><section><div class="section-heading"><h2>FAIL KETIGA</h2><span>${thirdBadges.filter(a=>a.unlocked()).length}/2 dicapai</span></div><div class="achievement-grid">${thirdBadges.map(achievementCard).join('')}</div></section><section class="records-section">`)};
const parentBeforeC011=renderParent;renderParent=function(){parentBeforeC011();app.innerHTML=app.innerHTML.replace(/Kes selesai<\/span><b>(\d+) \/ 10/g,'Kes selesai</span><b>$1 / 12').replace(/Lokasi ditemui<\/span><b>(\d+) \/ 10/g,'Lokasi ditemui</span><b>$1 / 12').replace(/Watak ditemui<\/span><b>(\d+) \/ 18/g,'Watak ditemui</span><b>$1 / 20').replace(/Bintang terbaik<\/span><b>(\d+) \/ 40/g,'Bintang terbaik</span><b>$1 / 48').replace('Sepuluh kes','Dua belas kes')};
const titleBeforeC011=renderTitle;renderTitle=function(){titleBeforeC011();app.innerHTML=app.innerHTML.replace('v1.5.0 by Zil-el-Saif','v1.6.0 by Zil-el-Saif')};
const resetBeforeC011=resetDetektifProgress;resetDetektifProgress=function(){resetBeforeC011();cases.C011={run:fresh11(),record:null};cases.C012={run:fresh12(),record:null};persist();render()};
const renderBeforeV16=render;render=function(){if(!isThirdArcCase(activeCase)||titleOpen||parentOpen||mapOpen||achievementsOpen||charactersOpen||guideOpen){renderBeforeV16();return}document.body?.classList?.remove('product-entry');document.querySelector('#sound').textContent=muted?'♪ Bunyi: Mati':'♪ Bunyi: Hidup';if(home){app.innerHTML=homeView();return}activeCase==='C011'?renderC011():renderC012()};
app.addEventListener('click',e=>{if(!isThirdArcCase(activeCase)||titleOpen||parentOpen||mapOpen||achievementsOpen||charactersOpen||guideOpen)return;const b=e.target.closest('button');if(!b||b.disabled||b.dataset.case)return;e.stopImmediatePropagation();sound('ui-click');activeCase==='C011'?handleC011Click(b):handleC012Click(b)},true);
app.addEventListener('change',e=>{if(!isThirdArcCase(activeCase))return;if(e.target?.dataset?.thirdLink!==undefined){state.links[Number(e.target.dataset.thirdLink)]=e.target.value}else if(e.target?.dataset?.c012Link!==undefined){state.links[Number(e.target.dataset.c012Link)]=e.target.value}else return;feedback='';wrong=false;persist();render()},true);
document.querySelector('footer span:last-child').textContent='v1.6.0 by Zil-el-Saif';render();
